### Rota para pegar os produtos
GET http://localhost:3000/produtos

### fechando a requicisao

### Rota criando o produto
POST http://localhost:3000/produtos
Content-Type: application/json

{
    "id":"2",
    "nome":"GTX 3070 8gb",
    "preco":14450
}

###

### Pegar produto pelo ID
GET http://localhost:3000/produtos/2
Content-Type: application/json

###
